### ISSUE TITLE
Some find IDs have disappeared from the csv result

### ISSUE THREAD

**Issue by leemordechai** [pyzmark/FLAME_DAI_transformation#4]
See the image for some of the listed find IDs. e.g. #2405 is missing. 

![image](https://github.com/pyzmark/FLAME_DAI_transformation/assets/16713928/c034ecc4-0f25-4fe4-89a9-6d5c06a7956f)

**Comment by pyzmark** [comment]
The problem is that the DAI never assigned the lost finds (e.g., 2405) a find category. It's caused them to silently fall out of the new 'finds' df that we cobbled together from the 'daip' raw data. I am going to build in a conditional or some kind of work around to make sure that they just receive null values for this field, but remain in the resulting df.

**Comment by pyzmark** [comment]
A new export has been uploaded that restores these finds. If you can check and confirm, we can close the issue.

**Comment by pyzmark** [comment]
This is in the new commit. Closing. Let me know if we need to reopen.
